/**
 * Enhanced Payout Engine — Phase H
 * Multi-currency payout support, period tracking, settlement runs.
 * Extends the existing payouts.ts FIFO consumption logic.
 */

import { prisma } from "@/lib/prisma";
import { availablePayoutBalance } from "./payouts";

export type PayoutRequestStatus = "requested" | "approved" | "processing" | "paid" | "failed";

/**
 * Create a payout request with period tracking and currency validation.
 */
export async function requestPayout(params: {
  affiliateId: string;
  amount: number;
  currency?: string;
  method?: string;
  period?: string;
  note?: string;
}) {
  const amount = Math.round(Number(params.amount));
  if (!(amount > 0)) throw new Error("Amount must be > 0");

  const aff = await prisma.affiliate.findUnique({ where: { id: params.affiliateId } });
  if (!aff) throw new Error("Affiliate not found");

  // Check min payout from campaign settings
  if (aff.campaignId) {
    const campaign = await prisma.affiliateCampaign.findUnique({
      where: { id: aff.campaignId },
      select: { minPayout: true },
    });
    if (campaign && amount < campaign.minPayout) {
      throw new Error(`Minimum payout is ${campaign.minPayout} cents`);
    }
  }

  const method = params.method || aff.payoutMethod || "bank";
  const currency = params.currency || "USD";

  // Balance check in transaction
  return prisma.$transaction(async (tx) => {
    const balance = await availablePayoutBalance({ affiliateId: params.affiliateId }, tx);
    if (amount > balance) {
      throw new Error(`Amount exceeds available balance (${balance})`);
    }
    return tx.affiliatePayout.create({
      data: {
        affiliateId: params.affiliateId,
        amount,
        currency,
        method,
        status: "requested",
        period: params.period || null,
        note: params.note || null,
      },
    });
  }, { maxWait: 20_000, timeout: 60_000 });
}

/**
 * Run a batch settlement for all eligible affiliates.
 * Finds all affiliates with payable commissions above their min payout,
 * creates payout requests automatically.
 */
export async function runSettlementBatch(opts?: { campaignId?: string }) {
  const where: Record<string, unknown> = { status: "active" };
  if (opts?.campaignId) where.campaignId = opts.campaignId;

  const affiliates = await prisma.affiliate.findMany({ where, select: { id: true } });
  const results: Array<{ affiliateId: string; payoutId?: string; error?: string }> = [];

  for (const aff of affiliates) {
    try {
      const balance = await availablePayoutBalance({ affiliateId: aff.id });
      if (balance <= 0) continue;

      // Check min payout
      const affDetails = await prisma.affiliate.findUnique({
        where: { id: aff.id },
        select: { campaignId: true },
      });
      let minPayout = 5000;
      if (affDetails?.campaignId) {
        const campaign = await prisma.affiliateCampaign.findUnique({
          where: { id: affDetails.campaignId },
          select: { minPayout: true },
        });
        if (campaign) minPayout = campaign.minPayout;
      }
      if (balance < minPayout) continue;

      const payout = await requestPayout({
        affiliateId: aff.id,
        amount: balance,
        period: new Date().toISOString().slice(0, 7),
        note: "Auto-generated by settlement batch",
      });
      results.push({ affiliateId: aff.id, payoutId: payout.id });
    } catch (e) {
      results.push({ affiliateId: aff.id, error: String(e) });
    }
  }

  return { processed: results.filter(r => r.payoutId).length, errors: results.filter(r => r.error), results };
}

/**
 * Get payout summary for an affiliate.
 */
export async function getPayoutSummary(affiliateId: string) {
  const [totalPaid, totalPending, totalRequested, recentPayouts] = await Promise.all([
    prisma.affiliatePayout.aggregate({
      where: { affiliateId, status: "paid" },
      _sum: { amount: true },
      _count: { _all: true },
    }),
    prisma.affiliatePayout.aggregate({
      where: { affiliateId, status: { in: ["requested","approved","processing"] } },
      _sum: { amount: true },
      _count: { _all: true },
    }),
    prisma.affiliatePayout.aggregate({
      where: { affiliateId },
      _sum: { amount: true },
      _count: { _all: true },
    }),
    prisma.affiliatePayout.findMany({
      where: { affiliateId },
      orderBy: { createdAt: "desc" },
      take: 10,
    }),
  ]);

  return {
    totalPaid: totalPaid._sum.amount ?? 0,
    paidCount: totalPaid._count._all,
    pendingAmount: totalPending._sum.amount ?? 0,
    pendingCount: totalPending._count._all,
    lifetimeEarnings: totalRequested._sum.amount ?? 0,
    lifetimeCount: totalRequested._count._all,
    recentPayouts,
  };
}
