
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Real DATABASE_URL (.env / environment) wins; generation-time fallback keeps
    // `prisma generate` working before any DB is configured.
    url: process.env.DATABASE_URL ?? "file:./var/saas.db",
  },
});
