import type { PlatformSignals, Property } from "./types";

/** Small builder so the dataset reads as tables. */
function p(
  present: boolean,
  rating: number,
  maxRating: number,
  reviewCount: number,
  reviewsRecent30: number,
  responseRate: number,
): PlatformSignals {
  return { present, rating, maxRating, reviewCount, reviewsRecent30, responseRate };
}

export const properties: Property[] = [
  {
    slug: "the-royal-sandpiper",
    name: "The Royal Sandpiper",
    city: "Cape Town",
    country: "South Africa",
    type: "Hotel",
    claimed: true,
    color: "emerald",
    signals: {
      platforms: {
        google: p(true, 4.6, 5, 820, 42, 0.95),
        booking: p(true, 8.9, 10, 1240, 88, 0.9),
        tripadvisor: p(true, 4.5, 5, 610, 31, 0.85),
        expedia: p(true, 4.3, 5, 260, 14, 0.6),
        airbnb: p(false, 0, 5, 0, 0, 0),
        hotels: p(true, 4.5, 5, 340, 22, 0.75),
        agoda: p(true, 8.7, 10, 180, 9, 0.5),
      },
      presence: {
        gbpCompleteness: 0.95,
        websiteQuality: 92,
        socialScore: 84,
        directoryListings: 6,
        localPackVisible: true,
      },
      quality: {
        service: 88,
        cleanliness: 92,
        valueForMoney: 74,
        location: 95,
        facilities: 82,
      },
      profile: {
        amenities: 90,
        visualContent: 85,
        sustainability: 60,
        accessibility: 55,
        directBookings: 40,
        starConsistency: 90,
        awards: 4,
      },
    },
  },
  {
    slug: "harbor-lights-inn",
    name: "Harbor Lights Inn",
    city: "Victoria",
    country: "Canada",
    type: "Guest House",
    claimed: true,
    color: "blue",
    signals: {
      platforms: {
        google: p(true, 4.8, 5, 410, 22, 0.88),
        booking: p(true, 9.2, 10, 560, 40, 0.8),
        tripadvisor: p(true, 4.7, 5, 330, 18, 0.9),
        expedia: p(false, 0, 5, 0, 0, 0),
        airbnb: p(false, 0, 5, 0, 0, 0),
        hotels: p(true, 9.0, 10, 210, 14, 0.7),
      },
      presence: {
        gbpCompleteness: 0.9,
        websiteQuality: 78,
        socialScore: 55,
        directoryListings: 4,
        localPackVisible: true,
      },
      quality: {
        service: 90,
        cleanliness: 93,
        valueForMoney: 85,
        location: 80,
        facilities: 70,
      },
      profile: {
        amenities: 78,
        visualContent: 70,
        sustainability: 50,
        accessibility: 45,
        directBookings: 55,
        starConsistency: 85,
        awards: 2,
      },
    },
  },
  {
    slug: "casa-verde-resort",
    name: "Casa Verde Resort",
    city: "Tulum",
    country: "Mexico",
    type: "Resort",
    claimed: true,
    color: "lime",
    signals: {
      platforms: {
        google: p(true, 4.1, 5, 520, 12, 0.2),
        booking: p(true, 8.2, 10, 680, 24, 0.15),
        tripadvisor: p(true, 3.9, 5, 410, 9, 0.1),
        expedia: p(true, 4.0, 5, 150, 5, 0.05),
        airbnb: p(false, 0, 5, 0, 0, 0),
        agoda: p(true, 8.0, 10, 90, 4, 0.1),
        trip: p(true, 4.2, 5, 45, 2, 0.05),
      },
      presence: {
        gbpCompleteness: 0.55,
        websiteQuality: 61,
        socialScore: 73,
        directoryListings: 3,
        localPackVisible: false,
      },
      quality: {
        service: 62,
        cleanliness: 68,
        valueForMoney: 55,
        location: 70,
        facilities: 60,
      },
      profile: {
        amenities: 75,
        visualContent: 58,
        sustainability: 45,
        accessibility: 35,
        directBookings: 20,
        starConsistency: 45,
        awards: 0,
      },
    },
  },
  {
    slug: "gilded-fox-boutique",
    name: "Gilded Fox Boutique Hotel",
    city: "Lisbon",
    country: "Portugal",
    type: "Boutique Hotel",
    claimed: true,
    color: "amber",
    signals: {
      platforms: {
        google: p(true, 4.7, 5, 230, 19, 0.98),
        booking: p(true, 9.4, 10, 310, 28, 0.95),
        tripadvisor: p(true, 4.6, 5, 180, 12, 0.9),
        expedia: p(true, 4.5, 5, 95, 7, 0.7),
        airbnb: p(true, 4.8, 5, 140, 10, 0.8),
        hotels: p(true, 4.6, 5, 120, 8, 0.85),
        agoda: p(true, 9.2, 10, 80, 5, 0.7),
        trip: p(true, 4.5, 5, 60, 4, 0.6),
      },
      presence: {
        gbpCompleteness: 1,
        websiteQuality: 88,
        socialScore: 91,
        directoryListings: 7,
        localPackVisible: true,
      },
      quality: {
        service: 92,
        cleanliness: 90,
        valueForMoney: 70,
        location: 88,
        facilities: 80,
      },
      profile: {
        amenities: 85,
        visualContent: 95,
        sustainability: 55,
        accessibility: 60,
        directBookings: 50,
        starConsistency: 95,
        awards: 3,
      },
    },
  },
  {
    slug: "sunset-ridge-cabins",
    name: "Sunset Ridge Cabins",
    city: "Banff",
    country: "Canada",
    type: "Vacation Rental",
    claimed: false,
    color: "orange",
    signals: {
      platforms: {
        google: p(true, 4.9, 5, 78, 9, 0.1),
        booking: p(true, 9.6, 10, 120, 16, 0.2),
        tripadvisor: p(true, 4.8, 5, 60, 5, 0.15),
        expedia: p(true, 4.7, 5, 40, 3, 0.1),
        airbnb: p(true, 4.95, 5, 260, 34, 0.4),
        vrbo: p(true, 4.8, 5, 70, 6, 0.25),
        agoda: p(true, 9.4, 10, 40, 3, 0.15),
      },
      presence: {
        gbpCompleteness: 0.6,
        websiteQuality: 54,
        socialScore: 62,
        directoryListings: 2,
        localPackVisible: false,
      },
      quality: {
        service: 85,
        cleanliness: 88,
        valueForMoney: 90,
        location: 78,
        facilities: 68,
      },
      profile: {
        amenities: 70,
        visualContent: 75,
        sustainability: 65,
        accessibility: 30,
        directBookings: 65,
        starConsistency: 80,
        awards: 1,
      },
    },
  },
  {
    slug: "marigold-hotel",
    name: "Marigold Hotel",
    city: "Jaipur",
    country: "India",
    type: "Hotel",
    claimed: true,
    color: "rose",
    signals: {
      platforms: {
        google: p(true, 3.4, 5, 990, 45, 0.3),
        booking: p(true, 7.1, 10, 1340, 92, 0.25),
        tripadvisor: p(true, 3.2, 5, 720, 38, 0.2),
        expedia: p(true, 3.5, 5, 300, 15, 0.1),
        airbnb: p(false, 0, 5, 0, 0, 0),
        agoda: p(true, 7.0, 10, 520, 30, 0.1),
        trip: p(true, 3.3, 5, 260, 14, 0.05),
      },
      presence: {
        gbpCompleteness: 0.4,
        websiteQuality: 48,
        socialScore: 35,
        directoryListings: 2,
        localPackVisible: false,
      },
      quality: {
        service: 40,
        cleanliness: 35,
        valueForMoney: 50,
        location: 60,
        facilities: 42,
      },
      profile: {
        amenities: 55,
        visualContent: 30,
        sustainability: 25,
        accessibility: 25,
        directBookings: 15,
        starConsistency: 30,
        awards: 0,
      },
    },
  },
  {
    slug: "driftwood-apartments",
    name: "Driftwood Apartments",
    city: "Byron Bay",
    country: "Australia",
    type: "Vacation Rental",
    claimed: true,
    color: "teal",
    signals: {
      platforms: {
        google: p(true, 4.4, 5, 180, 11, 0.5),
        booking: p(true, 8.6, 10, 220, 18, 0.45),
        tripadvisor: p(false, 0, 5, 0, 0, 0),
        expedia: p(true, 4.2, 5, 70, 4, 0.3),
        airbnb: p(true, 4.7, 5, 320, 29, 0.7),
        vrbo: p(true, 4.5, 5, 55, 4, 0.35),
        hotels: p(true, 8.4, 10, 90, 7, 0.4),
        agoda: p(true, 8.7, 10, 65, 5, 0.3),
      },
      presence: {
        gbpCompleteness: 0.75,
        websiteQuality: 70,
        socialScore: 66,
        directoryListings: 4,
        localPackVisible: true,
      },
      quality: {
        service: 78,
        cleanliness: 82,
        valueForMoney: 80,
        location: 85,
        facilities: 65,
      },
      profile: {
        amenities: 72,
        visualContent: 68,
        sustainability: 58,
        accessibility: 40,
        directBookings: 60,
        starConsistency: 75,
        awards: 1,
      },
    },
  },
  {
    slug: "novo-residences",
    name: "Novo Residences",
    city: "Austin",
    country: "USA",
    type: "Vacation Rental",
    claimed: false,
    color: "violet",
    signals: {
      platforms: {
        google: p(true, 3.8, 5, 45, 2, 0),
        booking: p(true, 7.6, 10, 62, 4, 0),
        tripadvisor: p(false, 0, 5, 0, 0, 0),
        expedia: p(true, 3.6, 5, 18, 1, 0),
        airbnb: p(true, 4.2, 5, 95, 6, 0.05),
      },
      presence: {
        gbpCompleteness: 0.2,
        websiteQuality: 30,
        socialScore: 20,
        directoryListings: 1,
        localPackVisible: false,
      },
      quality: {
        service: 55,
        cleanliness: 60,
        valueForMoney: 62,
        location: 72,
        facilities: 48,
      },
      profile: {
        amenities: 60,
        visualContent: 40,
        sustainability: 35,
        accessibility: 38,
        directBookings: 25,
        starConsistency: 40,
        awards: 0,
      },
    },
  },
  {
    slug: "la-couronne-palace",
    name: "La Couronne Palace",
    city: "Paris",
    country: "France",
    type: "Boutique Hotel",
    claimed: true,
    color: "sky",
    signals: {
      platforms: {
        google: p(true, 4.9, 5, 640, 51, 1),
        booking: p(true, 9.7, 10, 820, 73, 1),
        tripadvisor: p(true, 4.9, 5, 500, 40, 0.97),
        expedia: p(true, 4.8, 5, 210, 16, 0.85),
        airbnb: p(false, 0, 5, 0, 0, 0),
        hotels: p(true, 4.8, 5, 300, 24, 0.9),
        agoda: p(true, 9.5, 10, 180, 13, 0.8),
        trip: p(true, 4.8, 5, 130, 9, 0.75),
      },
      presence: {
        gbpCompleteness: 1,
        websiteQuality: 96,
        socialScore: 94,
        directoryListings: 8,
        localPackVisible: true,
      },
      quality: {
        service: 96,
        cleanliness: 95,
        valueForMoney: 72,
        location: 98,
        facilities: 94,
      },
      profile: {
        amenities: 95,
        visualContent: 92,
        sustainability: 70,
        accessibility: 65,
        directBookings: 45,
        starConsistency: 98,
        awards: 6,
      },
    },
  },
  {
    slug: "quiet-waters-bnb",
    name: "Quiet Waters B&B",
    city: "Lake District",
    country: "UK",
    type: "Guest House",
    claimed: false,
    color: "cyan",
    signals: {
      platforms: {
        google: p(true, 4.5, 5, 95, 6, 0.05),
        booking: p(true, 8.8, 10, 140, 11, 0.08),
        tripadvisor: p(true, 4.4, 5, 80, 4, 0.1),
        expedia: p(false, 0, 5, 0, 0, 0),
        airbnb: p(false, 0, 5, 0, 0, 0),
      },
      presence: {
        gbpCompleteness: 0.5,
        websiteQuality: 44,
        socialScore: 28,
        directoryListings: 2,
        localPackVisible: false,
      },
      quality: {
        service: 82,
        cleanliness: 85,
        valueForMoney: 88,
        location: 68,
        facilities: 55,
      },
      profile: {
        amenities: 62,
        visualContent: 55,
        sustainability: 52,
        accessibility: 28,
        directBookings: 48,
        starConsistency: 65,
        awards: 0,
      },
    },
  },
];

export function findProperty(slug: string): Property | undefined {
  return properties.find((prop) => prop.slug === slug);
}
